/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Mon Aug 28 08:40:29 GMT 2023
 */

package com.google.javascript.jscomp;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class TypedScopeCreator_ESTest_scaffolding {

  @org.junit.Rule
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "com.google.javascript.jscomp.TypedScopeCreator"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("user.dir", "/home/liumengjiao/Desktop/CI/bugs/Closure_17_buggy"); 
    java.lang.System.setProperty("java.io.tmpdir", "/tmp"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(TypedScopeCreator_ESTest_scaffolding.class.getClassLoader() ,
      "com.google.javascript.rhino.Node$SiblingNodeIterable",
      "com.google.javascript.jscomp.TypedScopeCreator",
      "com.google.javascript.rhino.jstype.JSType",
      "com.google.javascript.rhino.JSDocInfo$Visibility",
      "com.google.javascript.rhino.jstype.PrototypeObjectType",
      "com.google.javascript.rhino.Node$StringNode",
      "com.google.javascript.rhino.Node$AncestorIterable",
      "com.google.javascript.jscomp.NodeTraversal$Callback",
      "com.google.javascript.jscomp.ScopeCreator",
      "com.google.javascript.jscomp.TypedScopeCreator$AbstractScopeBuilder",
      "com.google.javascript.jscomp.TypedScopeCreator$GlobalScopeBuilder",
      "com.google.javascript.jscomp.TypeValidator",
      "com.google.javascript.rhino.Node$SideEffectFlags",
      "com.google.javascript.rhino.jstype.StaticScope",
      "com.google.javascript.jscomp.CodingConvention$ObjectLiteralCast",
      "com.google.javascript.jscomp.SourceExcerptProvider",
      "com.google.javascript.jscomp.CodingConvention$SubclassRelationship",
      "com.google.javascript.rhino.Node$PropListItem",
      "com.google.javascript.rhino.jstype.JSTypeRegistry",
      "com.google.javascript.rhino.Node$NumberNode",
      "com.google.javascript.jscomp.Scope",
      "com.google.javascript.rhino.ErrorReporter",
      "com.google.javascript.rhino.jstype.ObjectType",
      "com.google.javascript.rhino.Node",
      "com.google.javascript.jscomp.CheckLevel",
      "com.google.javascript.jscomp.DefaultCodingConvention",
      "com.google.javascript.rhino.Node$FileLevelJsDocBuilder",
      "com.google.javascript.rhino.Node$NodeMismatch",
      "com.google.javascript.jscomp.NodeTraversal",
      "com.google.javascript.rhino.jstype.FunctionPrototypeType",
      "com.google.javascript.jscomp.CodingConvention$DelegateRelationship",
      "com.google.javascript.rhino.jstype.JSTypeNative",
      "com.google.javascript.jscomp.DiagnosticType",
      "com.google.javascript.jscomp.TypedScopeCreator$LocalScopeBuilder",
      "com.google.javascript.jscomp.CodingConvention$SubclassType",
      "com.google.javascript.rhino.jstype.JSType$1",
      "com.google.javascript.rhino.JSTypeExpression",
      "com.google.javascript.rhino.jstype.FunctionType",
      "com.google.javascript.jscomp.CodingConvention",
      "com.google.javascript.jscomp.AbstractCompiler",
      "com.google.javascript.rhino.JSDocInfo",
      "com.google.javascript.jscomp.Compiler"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(TypedScopeCreator_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "com.google.javascript.rhino.jstype.JSType$1",
      "com.google.javascript.rhino.jstype.JSType",
      "com.google.javascript.rhino.jstype.ObjectType",
      "com.google.javascript.jscomp.DiagnosticType",
      "com.google.javascript.jscomp.CheckLevel",
      "com.google.javascript.jscomp.TypedScopeCreator",
      "com.google.javascript.jscomp.NodeTraversal$AbstractShallowStatementCallback",
      "com.google.javascript.jscomp.TypedScopeCreator$DiscoverEnumsAndTypedefs",
      "com.google.javascript.jscomp.TypedScopeCreator$AbstractScopeBuilder",
      "com.google.javascript.jscomp.TypedScopeCreator$GlobalScopeBuilder",
      "com.google.javascript.jscomp.TypedScopeCreator$LocalScopeBuilder",
      "com.google.javascript.jscomp.TypedScopeCreator$StubDeclaration",
      "com.google.javascript.jscomp.TypedScopeCreator$DeferredSetType",
      "com.google.javascript.jscomp.TypedScopeCreator$AbstractScopeBuilder$CollectProperties",
      "com.google.javascript.rhino.jstype.JSTypeNative",
      "com.google.javascript.rhino.jstype.TernaryValue",
      "com.google.javascript.rhino.Node",
      "com.google.javascript.jscomp.AbstractPeepholeOptimization",
      "com.google.javascript.jscomp.StatementFusion",
      "com.google.javascript.rhino.Node$NumberNode",
      "com.google.javascript.jscomp.MoveFunctionDeclarations",
      "com.google.javascript.rhino.Node$StringNode",
      "com.google.javascript.jscomp.NodeTraversal$AbstractPostOrderCallback",
      "com.google.javascript.jscomp.StrictModeCheck",
      "com.google.javascript.jscomp.NodeTraversal",
      "com.google.javascript.jscomp.SyntacticScopeCreator",
      "com.google.javascript.jscomp.SyntacticScopeCreator$DefaultRedeclarationHandler",
      "com.google.javascript.jscomp.DefaultCodingConvention",
      "com.google.javascript.jscomp.ClosureCodingConvention",
      "com.google.javascript.jscomp.GoogleCodingConvention",
      "com.google.javascript.jscomp.CheckMissingGetCssName",
      "com.google.javascript.jscomp.CombinedCompilerPass",
      "com.google.javascript.jscomp.ExternExportsPass",
      "com.google.javascript.rhino.Kit",
      "com.google.javascript.rhino.Node$PropListItem",
      "com.google.javascript.jscomp.Denormalize",
      "com.google.javascript.jscomp.PeepholeFoldWithTypes",
      "com.google.javascript.jscomp.PeepholeFoldConstants",
      "com.google.javascript.jscomp.OptimizeArgumentsArray",
      "com.google.javascript.rhino.Token",
      "com.google.javascript.jscomp.ProcessClosurePrimitives",
      "com.google.javascript.rhino.Node$AncestorIterable",
      "com.google.javascript.rhino.Node$AncestorIterable$1",
      "com.google.javascript.jscomp.PeepholeOptimizationsPass",
      "com.google.javascript.jscomp.InferJSDocInfo",
      "com.google.javascript.jscomp.SyntheticAst",
      "com.google.javascript.jscomp.PrepareAst$PrepareAnnotations",
      "com.google.javascript.rhino.JSDocInfo",
      "com.google.javascript.jscomp.SourceFile",
      "com.google.javascript.jscomp.JSSourceFile",
      "com.google.javascript.jscomp.SourceFile$OnDisk",
      "com.google.javascript.jscomp.Denormalize$StripConstantAnnotations",
      "com.google.javascript.jscomp.GatherRawExports",
      "com.google.javascript.rhino.Node$NodeMismatch",
      "com.google.javascript.rhino.Node$SiblingNodeIterable",
      "com.google.javascript.jscomp.MakeDeclaredNamesUnique",
      "com.google.javascript.jscomp.MinimizeExitPoints",
      "com.google.javascript.rhino.Node$SideEffectFlags",
      "com.google.javascript.jscomp.SourceFile$Generated",
      "com.google.javascript.jscomp.JsAst",
      "com.google.javascript.jscomp.UnfoldCompoundAssignments",
      "com.google.javascript.rhino.JSDocInfo$LazilyInitializedInfo",
      "com.google.javascript.jscomp.CompilerInput",
      "com.google.javascript.jscomp.ConvertToDottedProperties",
      "com.google.javascript.jscomp.GroupVariableDeclarations",
      "com.google.javascript.jscomp.CheckAccidentalSemicolon",
      "com.google.javascript.jscomp.LineNumberCheck",
      "com.google.javascript.jscomp.CheckPropertyOrder",
      "com.google.javascript.jscomp.MemoizedScopeCreator",
      "com.google.javascript.jscomp.VarCheck",
      "com.google.javascript.jscomp.ConstCheck",
      "com.google.javascript.jscomp.Normalize$PropagateConstantAnnotationsOverVars",
      "com.google.javascript.rhino.Node$FileLevelJsDocBuilder",
      "com.google.javascript.jscomp.CheckSideEffects",
      "com.google.javascript.jscomp.SourceInformationAnnotator",
      "com.google.javascript.jscomp.Normalize$NormalizeStatements",
      "com.google.javascript.jscomp.CheckRegExp",
      "com.google.javascript.jscomp.LinkedFlowScope",
      "com.google.javascript.jscomp.LinkedFlowScope$FlatFlowScopeCache",
      "com.google.javascript.jscomp.FindExportableNodes",
      "com.google.javascript.jscomp.JSError",
      "com.google.javascript.jscomp.JsMessageVisitor",
      "com.google.javascript.jscomp.ReplaceMessages",
      "com.google.javascript.jscomp.GatherSideEffectSubexpressionsCallback$CopySideEffectSubexpressions",
      "com.google.javascript.jscomp.GatherSideEffectSubexpressionsCallback",
      "com.google.javascript.jscomp.UnreachableCodeElimination",
      "com.google.javascript.jscomp.CoalesceVariableNames$1",
      "com.google.javascript.jscomp.CoalesceVariableNames",
      "com.google.javascript.jscomp.JSModule",
      "com.google.javascript.jscomp.FunctionNames",
      "com.google.javascript.jscomp.SourceFile$Preloaded",
      "com.google.javascript.jscomp.Normalize$VerifyConstants",
      "com.google.javascript.jscomp.Scope",
      "com.google.javascript.jscomp.RenameLabels",
      "com.google.javascript.jscomp.RenameLabels$ProcessLabels",
      "com.google.javascript.jscomp.CheckGlobalThis",
      "com.google.javascript.jscomp.DiagnosticGroup",
      "com.google.javascript.jscomp.TypeCheck",
      "com.google.javascript.jscomp.AnonymousFunctionNamingCallback",
      "com.google.javascript.jscomp.VariableMap",
      "com.google.javascript.rhino.SimpleErrorReporter",
      "com.google.javascript.jscomp.CrossModuleCodeMotion"
    );
  }
}
